/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedServersRouteImport } from './routes/_authenticated/servers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAppsNewRouteImport } from './routes/_authenticated/apps.new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServersRoute = AuthenticatedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsNewRoute = AuthenticatedAppsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/servers': typeof AuthenticatedServersRoute
  '/apps/new': typeof AuthenticatedAppsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/servers': typeof AuthenticatedServersRoute
  '/apps/new': typeof AuthenticatedAppsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/servers': typeof AuthenticatedServersRoute
  '/_authenticated/apps/new': typeof AuthenticatedAppsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/apps' | '/dashboard' | '/servers' | '/apps/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/apps' | '/dashboard' | '/servers' | '/apps/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apps'
    | '/_authenticated/dashboard'
    | '/_authenticated/servers'
    | '/_authenticated/apps/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servers': {
      id: '/_authenticated/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AuthenticatedServersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/new': {
      id: '/_authenticated/apps/new'
      path: '/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AuthenticatedAppsNewRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
  }
}

interface AuthenticatedAppsRouteChildren {
  AuthenticatedAppsNewRoute: typeof AuthenticatedAppsNewRoute
}

const AuthenticatedAppsRouteChildren: AuthenticatedAppsRouteChildren = {
  AuthenticatedAppsNewRoute: AuthenticatedAppsNewRoute,
}

const AuthenticatedAppsRouteWithChildren =
  AuthenticatedAppsRoute._addFileChildren(AuthenticatedAppsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedServersRoute: typeof AuthenticatedServersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedServersRoute: AuthenticatedServersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
