/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedAppsNewRouteImport } from './routes/_authenticated/apps.new'
import { Route as ApiPublicAppsIndexRouteImport } from './routes/api/public/apps.index'
import { Route as ApiPublicAppsIdIconRouteImport } from './routes/api/public/apps.$id.icon'
import { Route as ApiPublicAppsIdDownloadRouteImport } from './routes/api/public/apps.$id.download'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsNewRoute = AuthenticatedAppsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const ApiPublicAppsIndexRoute = ApiPublicAppsIndexRouteImport.update({
  id: '/api/public/apps/',
  path: '/api/public/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppsIdIconRoute = ApiPublicAppsIdIconRouteImport.update({
  id: '/api/public/apps/$id/icon',
  path: '/api/public/apps/$id/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppsIdDownloadRoute = ApiPublicAppsIdDownloadRouteImport.update({
  id: '/api/public/apps/$id/download',
  path: '/api/public/apps/$id/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/apps/new': typeof AuthenticatedAppsNewRoute
  '/api/public/apps/': typeof ApiPublicAppsIndexRoute
  '/api/public/apps/$id/download': typeof ApiPublicAppsIdDownloadRoute
  '/api/public/apps/$id/icon': typeof ApiPublicAppsIdIconRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/apps/new': typeof AuthenticatedAppsNewRoute
  '/api/public/apps': typeof ApiPublicAppsIndexRoute
  '/api/public/apps/$id/download': typeof ApiPublicAppsIdDownloadRoute
  '/api/public/apps/$id/icon': typeof ApiPublicAppsIdIconRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/apps/new': typeof AuthenticatedAppsNewRoute
  '/api/public/apps/': typeof ApiPublicAppsIndexRoute
  '/api/public/apps/$id/download': typeof ApiPublicAppsIdDownloadRoute
  '/api/public/apps/$id/icon': typeof ApiPublicAppsIdIconRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/apps'
    | '/dashboard'
    | '/apps/new'
    | '/api/public/apps/'
    | '/api/public/apps/$id/download'
    | '/api/public/apps/$id/icon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/apps'
    | '/dashboard'
    | '/apps/new'
    | '/api/public/apps'
    | '/api/public/apps/$id/download'
    | '/api/public/apps/$id/icon'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/apps'
    | '/_authenticated/dashboard'
    | '/_authenticated/apps/new'
    | '/api/public/apps/'
    | '/api/public/apps/$id/download'
    | '/api/public/apps/$id/icon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAppsIndexRoute: typeof ApiPublicAppsIndexRoute
  ApiPublicAppsIdDownloadRoute: typeof ApiPublicAppsIdDownloadRoute
  ApiPublicAppsIdIconRoute: typeof ApiPublicAppsIdIconRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/new': {
      id: '/_authenticated/apps/new'
      path: '/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AuthenticatedAppsNewRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/api/public/apps/': {
      id: '/api/public/apps/'
      path: '/api/public/apps'
      fullPath: '/api/public/apps/'
      preLoaderRoute: typeof ApiPublicAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apps/$id/icon': {
      id: '/api/public/apps/$id/icon'
      path: '/api/public/apps/$id/icon'
      fullPath: '/api/public/apps/$id/icon'
      preLoaderRoute: typeof ApiPublicAppsIdIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apps/$id/download': {
      id: '/api/public/apps/$id/download'
      path: '/api/public/apps/$id/download'
      fullPath: '/api/public/apps/$id/download'
      preLoaderRoute: typeof ApiPublicAppsIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppsRouteChildren {
  AuthenticatedAppsNewRoute: typeof AuthenticatedAppsNewRoute
}

const AuthenticatedAppsRouteChildren: AuthenticatedAppsRouteChildren = {
  AuthenticatedAppsNewRoute: AuthenticatedAppsNewRoute,
}

const AuthenticatedAppsRouteWithChildren =
  AuthenticatedAppsRoute._addFileChildren(AuthenticatedAppsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAppsIndexRoute: ApiPublicAppsIndexRoute,
  ApiPublicAppsIdDownloadRoute: ApiPublicAppsIdDownloadRoute,
  ApiPublicAppsIdIconRoute: ApiPublicAppsIdIconRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
