/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBooksRouteImport } from './routes/_authenticated/books'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedBooksNewRouteImport } from './routes/_authenticated/books.new'
import { Route as AuthenticatedAppsNewRouteImport } from './routes/_authenticated/apps.new'
import { Route as ApiPublicAppsIndexRouteImport } from './routes/api/public/apps.index'
import { Route as AuthenticatedBooksIdEditRouteImport } from './routes/_authenticated/books.$id.edit'
import { Route as AuthenticatedAppsIdEditRouteImport } from './routes/_authenticated/apps.$id.edit'
import { Route as ApiPublicAppsIdIconRouteImport } from './routes/api/public/apps.$id.icon'
import { Route as ApiPublicAppsIdDownloadRouteImport } from './routes/api/public/apps.$id.download'
import { Route as ApiPublicAppsIdScreenshotIndexRouteImport } from './routes/api/public/apps.$id.screenshot.$index'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksRoute = AuthenticatedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksNewRoute = AuthenticatedBooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBooksRoute,
} as any)
const AuthenticatedAppsNewRoute = AuthenticatedAppsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const ApiPublicAppsIndexRoute = ApiPublicAppsIndexRouteImport.update({
  id: '/api/public/apps/',
  path: '/api/public/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBooksIdEditRoute =
  AuthenticatedBooksIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedBooksRoute,
  } as any)
const AuthenticatedAppsIdEditRoute = AuthenticatedAppsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const ApiPublicAppsIdIconRoute = ApiPublicAppsIdIconRouteImport.update({
  id: '/api/public/apps/$id/icon',
  path: '/api/public/apps/$id/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppsIdDownloadRoute = ApiPublicAppsIdDownloadRouteImport.update({
  id: '/api/public/apps/$id/download',
  path: '/api/public/apps/$id/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAppsIdScreenshotIndexRoute =
  ApiPublicAppsIdScreenshotIndexRouteImport.update({
    id: '/api/public/apps/$id/screenshot/$index',
    path: '/api/public/apps/$id/screenshot/$index',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/books': typeof AuthenticatedBooksRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/apps/new': typeof AuthenticatedAppsNewRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/apps/$id/edit': typeof AuthenticatedAppsIdEditRoute
  '/books/$id/edit': typeof AuthenticatedBooksIdEditRoute
  '/api/public/apps/': typeof ApiPublicAppsIndexRoute
  '/api/public/apps/$id/download': typeof ApiPublicAppsIdDownloadRoute
  '/api/public/apps/$id/icon': typeof ApiPublicAppsIdIconRoute
  '/api/public/apps/$id/screenshot/$index': typeof ApiPublicAppsIdScreenshotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/books': typeof AuthenticatedBooksRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/apps/new': typeof AuthenticatedAppsNewRoute
  '/books/new': typeof AuthenticatedBooksNewRoute
  '/apps/$id/edit': typeof AuthenticatedAppsIdEditRoute
  '/books/$id/edit': typeof AuthenticatedBooksIdEditRoute
  '/api/public/apps': typeof ApiPublicAppsIndexRoute
  '/api/public/apps/$id/download': typeof ApiPublicAppsIdDownloadRoute
  '/api/public/apps/$id/icon': typeof ApiPublicAppsIdIconRoute
  '/api/public/apps/$id/screenshot/$index': typeof ApiPublicAppsIdScreenshotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRouteWithChildren
  '/_authenticated/books': typeof AuthenticatedBooksRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/apps/new': typeof AuthenticatedAppsNewRoute
  '/_authenticated/books/new': typeof AuthenticatedBooksNewRoute
  '/_authenticated/apps/$id/edit': typeof AuthenticatedAppsIdEditRoute
  '/_authenticated/books/$id/edit': typeof AuthenticatedBooksIdEditRoute
  '/api/public/apps/': typeof ApiPublicAppsIndexRoute
  '/api/public/apps/$id/download': typeof ApiPublicAppsIdDownloadRoute
  '/api/public/apps/$id/icon': typeof ApiPublicAppsIdIconRoute
  '/api/public/apps/$id/screenshot/$index': typeof ApiPublicAppsIdScreenshotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/apps'
    | '/books'
    | '/dashboard'
    | '/apps/new'
    | '/books/new'
    | '/apps/$id/edit'
    | '/books/$id/edit'
    | '/api/public/apps/'
    | '/api/public/apps/$id/download'
    | '/api/public/apps/$id/icon'
    | '/api/public/apps/$id/screenshot/$index'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/apps'
    | '/books'
    | '/dashboard'
    | '/apps/new'
    | '/books/new'
    | '/apps/$id/edit'
    | '/books/$id/edit'
    | '/api/public/apps'
    | '/api/public/apps/$id/download'
    | '/api/public/apps/$id/icon'
    | '/api/public/apps/$id/screenshot/$index'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/apps'
    | '/_authenticated/books'
    | '/_authenticated/dashboard'
    | '/_authenticated/apps/new'
    | '/_authenticated/books/new'
    | '/_authenticated/apps/$id/edit'
    | '/_authenticated/books/$id/edit'
    | '/api/public/apps/'
    | '/api/public/apps/$id/download'
    | '/api/public/apps/$id/icon'
    | '/api/public/apps/$id/screenshot/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiPublicAppsIndexRoute: typeof ApiPublicAppsIndexRoute
  ApiPublicAppsIdDownloadRoute: typeof ApiPublicAppsIdDownloadRoute
  ApiPublicAppsIdIconRoute: typeof ApiPublicAppsIdIconRoute
  ApiPublicAppsIdScreenshotIndexRoute: typeof ApiPublicAppsIdScreenshotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/new': {
      id: '/_authenticated/books/new'
      path: '/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AuthenticatedBooksNewRouteImport
      parentRoute: typeof AuthenticatedBooksRoute
    }
    '/_authenticated/apps/new': {
      id: '/_authenticated/apps/new'
      path: '/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AuthenticatedAppsNewRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/api/public/apps/': {
      id: '/api/public/apps/'
      path: '/api/public/apps'
      fullPath: '/api/public/apps/'
      preLoaderRoute: typeof ApiPublicAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/books/$id/edit': {
      id: '/_authenticated/books/$id/edit'
      path: '/$id/edit'
      fullPath: '/books/$id/edit'
      preLoaderRoute: typeof AuthenticatedBooksIdEditRouteImport
      parentRoute: typeof AuthenticatedBooksRoute
    }
    '/_authenticated/apps/$id/edit': {
      id: '/_authenticated/apps/$id/edit'
      path: '/$id/edit'
      fullPath: '/apps/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppsIdEditRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/api/public/apps/$id/icon': {
      id: '/api/public/apps/$id/icon'
      path: '/api/public/apps/$id/icon'
      fullPath: '/api/public/apps/$id/icon'
      preLoaderRoute: typeof ApiPublicAppsIdIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apps/$id/download': {
      id: '/api/public/apps/$id/download'
      path: '/api/public/apps/$id/download'
      fullPath: '/api/public/apps/$id/download'
      preLoaderRoute: typeof ApiPublicAppsIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apps/$id/screenshot/$index': {
      id: '/api/public/apps/$id/screenshot/$index'
      path: '/api/public/apps/$id/screenshot/$index'
      fullPath: '/api/public/apps/$id/screenshot/$index'
      preLoaderRoute: typeof ApiPublicAppsIdScreenshotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppsRouteChildren {
  AuthenticatedAppsNewRoute: typeof AuthenticatedAppsNewRoute
  AuthenticatedAppsIdEditRoute: typeof AuthenticatedAppsIdEditRoute
}

const AuthenticatedAppsRouteChildren: AuthenticatedAppsRouteChildren = {
  AuthenticatedAppsNewRoute: AuthenticatedAppsNewRoute,
  AuthenticatedAppsIdEditRoute: AuthenticatedAppsIdEditRoute,
}

const AuthenticatedAppsRouteWithChildren =
  AuthenticatedAppsRoute._addFileChildren(AuthenticatedAppsRouteChildren)

interface AuthenticatedBooksRouteChildren {
  AuthenticatedBooksNewRoute: typeof AuthenticatedBooksNewRoute
  AuthenticatedBooksIdEditRoute: typeof AuthenticatedBooksIdEditRoute
}

const AuthenticatedBooksRouteChildren: AuthenticatedBooksRouteChildren = {
  AuthenticatedBooksNewRoute: AuthenticatedBooksNewRoute,
  AuthenticatedBooksIdEditRoute: AuthenticatedBooksIdEditRoute,
}

const AuthenticatedBooksRouteWithChildren =
  AuthenticatedBooksRoute._addFileChildren(AuthenticatedBooksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRouteWithChildren
  AuthenticatedBooksRoute: typeof AuthenticatedBooksRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRouteWithChildren,
  AuthenticatedBooksRoute: AuthenticatedBooksRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiPublicAppsIndexRoute: ApiPublicAppsIndexRoute,
  ApiPublicAppsIdDownloadRoute: ApiPublicAppsIdDownloadRoute,
  ApiPublicAppsIdIconRoute: ApiPublicAppsIdIconRoute,
  ApiPublicAppsIdScreenshotIndexRoute: ApiPublicAppsIdScreenshotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
